config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/', to: 'home#index'
  get '/login', to: 'home#index'
  resources :tables, to: 'home#index'
  resources :tournaments, only: %i(index show), to: 'home#index'
  get '/settings', to: 'home#index'

  namespace :api, format: 'json' do
    resources :tests, only: %i(create)
    resource :session, only: %i(create destroy)
    resources :players, only: %i(show update)
    resources :tables do
      resources :table_messages, only: %i(index create)
    end

    resources :tournaments, only: %i(index show create) do
      post :start, on: :member
      post :entry, on: :member
    end

    resource :game_dealer, only: %i(create) do
      post :start, on: :collection
      post :take_seat, on: :collection
      post :add_npc_player, on: :collection
      post :retry_npc_player_action, on: :collection
    end
  end

  namespace :admin do
    get '/', to: 'home#index'
    resources :client_versions, only: %i(create)
    resources :game_hands
    resources :tables
    resources :tournaments do
      post :debug_entry, on: :member
    end
  end

  get 'auth/facebook/callback', to: 'players/omniauth_callbacks#facebook'
  get 'auth/twitter/callback', to: 'players/omniauth_callbacks#twitter'
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController
  def index
    @players = Player.all.to_a
    @other_service_accounts = OtherServiceAccount.all.to_a
    @tables = Table.all.to_a
    @client_versions = ClientVersion.order(created_at: :desc).limit(3)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/admin/home/index.html.slim
.
  ul
    - @client_versions.each do |client_version|
      li= client_version.version
  = form_with url: admin_client_versions_path do |form|
    = form.submit

= link_to 'トーナメント', admin_tournaments_path

table.table.table-bordered
  - @tables.each do |table|
    tr
      td= "#{table.name}(#{table.id})"
      td
        .
          = link_to '詳細', admin_table_path(id: table.id), class: %w(btn btn-outline-primary)
        .mt-2
          = link_to 'Delete', admin_table_path(id: table.id), class: %w(btn btn-outline-secondary), method: :delete

.
  - if @players.present?
    .container
      - @players.each do |player|
        - next if player.is_npc?
        .row
          .col-3
            = "(#{player.id}) #{player.name}"
          .col-3
            img src=player.profile_image_url style="max-width: 80px"
          .col-3
            = player.other_service_accounts.map(&:provider).join(':')
          .col-3
            = l player.created_at
  - else
    | no players

hr

.
  - if @other_service_accounts
    table style="border: 1px solid black"
      tr
        th Player ID
        th Provider
        th UID
      - @other_service_accounts.each do |other_service_account|
        tr
          td= other_service_account.player_id
          td= other_service_account.provider
          td= other_service_account.uid
  - else
    | 連携済みユーザはいません。

hr